# Generated by Django 3.0.3 on 2020-03-01 21:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_auto_20200301_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='date',
            field=models.CharField(default=datetime.datetime(2020, 3, 1, 21, 0, 47, 545782, tzinfo=utc), max_length=200),
        ),
    ]
