# Generated by Django 3.0.3 on 2020-03-02 19:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0006_auto_20200302_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='date',
            field=models.CharField(default=datetime.datetime(2020, 3, 2, 19, 37, 1, 144281, tzinfo=utc), max_length=200),
        ),
    ]
