# Generated by Django 3.0.3 on 2020-03-03 00:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0009_auto_20200302_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='date',
            field=models.CharField(default=datetime.datetime(2020, 3, 3, 0, 17, 9, 264493, tzinfo=utc), max_length=200),
        ),
    ]
